### ISSUE TITLE
What container to use that contains multiple tools

### ISSUE THREAD

**Issue by nh13** [nf-core/fastquorum#1]
We have a process that executes multiple tools (`samtools`, `fgbio`, and `bwa`).  How do we set the container directive?

See: https://github.com/fulcrumgenomics/fgcons/blob/663e0f98ed74ded36cd137f4eb23960e81d8849b/modules/local/align_bam/main.nf#L5-L8

**Comment by FriederikeHanssen** [comment]
For this, usually just adding all the tools here https://github.com/BioContainers/multi-package-containers/blob/master/combinations/hash.tsv should be enough. Then a mulled container is generated and can be added like here: https://github.com/nf-core/modules/blob/2c70c1c1951aaf884d2e8d8d9c871db79f7b35aa/modules/bwamem2/mem/main.nf#L7

**Comment by SPPearce** [comment]
FYI @nh13, I've just requested this container to be made by following the link above. It'll probably be a day or two for it to be generated.
