### ISSUE TITLE
Consensus mapped BAM replacing initial mapped file

### ISSUE THREAD

**Issue by FerriolCalvet** [nf-core/fastquorum#19]
### Description of the bug

We are running the pipeline in duplex mode for some samples and I was interested in checking how the reads progress through the different steps.
I realized that the first mapping of the reads is stored in `align/` directory with the name `${meta.id}.mapped.bam`, and then as the pipeline keeps going through the following steps this file is replaced by the aligned version of the consensus reads instead of the raw reads.
I think this happens since the value of `${meta.id}` has not changed and as the module used is exactly the same with a different name, the files get replaced. I am not sure whether changing the `${meta.id}` into something like `${meta.id}.cons` would be the best way to proceed or if you have any other ideas on how to fix this.
(It is not a bug that interferes with the quality of the output, but it is losing some of the intermediate files.)

Thank you!

Ferriol

PS: I have seen that you are updating the `fgbio` modules in the `nf-core/modules` repo. Are you planning to update this pipeline with them?

**Comment by nh13** [comment]
I think this is a bug, and we should change the suffix produced in the consensus alignment is run [here](https://github.com/nf-core/fastquorum/blob/09a6ae27ce917f2a4b15d2c5396acb562f9047aa/modules/local/align_bam/main.nf#L46) and [here](https://github.com/nf-core/fastquorum/blob/09a6ae27ce917f2a4b15d2c5396acb562f9047aa/modules/local/align_bam/main.nf#L48) via a new input parameter to the process from the main workflow.

**Comment by nh13** [comment]
I think this will be fixed in https://github.com/nf-core/fastquorum/pull/36

**Comment by nh13** [comment]
F
