### ISSUE TITLE
Error in profile test run

### ISSUE THREAD

**Issue by Anushi** [nf-core/fastquorum#28]
### Description of the bug

I tried running profile test run using the command :

**nextflow run nf-core/fastquorum -profile test,docker --outdir profile_test_run**

This threw error -
ERROR ~ ERROR: Validation of pipeline parameters failed!

 -- Check '.nextflow.log' file for details
ERROR ~ * Missing required parameter: --ref_fasta

 -- Check '.nextflow.log' file for details

After this, I tried providing reference genome to the parameter --ref_fasta. It threw error :-

**nextflow run nf-core/fastquorum -profile test,docker --outdir profile_test_run --ref_fasta hs37d5.fa -r dev**

-[nf-core/fastquorum] Pipeline completed with errors-
ERROR ~ Error executing process > 'NFCORE_FASTQUORUM:FASTQUORUM:INPUT_CHECK:SAMPLESHEET_CHECK (samplesheet_test_illumina_amplicon.csv)'

Caused by:
  Process NFCORE_FASTQUORUM:FASTQUORUM:INPUT_CHECK:SAMPLESHEET_CHECK (samplesheet_test_illumina_amplicon.csv) terminated with an error exit status (1)

Command executed:

  check_samplesheet.py \
      samplesheet_test_illumina_amplicon.csv \
      samplesheet.valid.csv

  cat <<-END_VERSIONS > versions.yml
  "NFCORE_FASTQUORUM:FASTQUORUM:INPUT_CHECK:SAMPLESHEET_CHECK":
      python: $(python --version | sed 's/Python //g')
  END_VERSIONS

Command exit status:
  1

Command output:
  (empty)

Command error:
  WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
  [CRITICAL] The sample sheet must contain the column headers: fastq_1, read_structure, sample, fastq_2.

Seems like column information issue in samplesheet_test_illumina_amplicon.csv. I wonder if it is possible to update the file.  I want to give a test try for fastquorum. Many thanks !

### Command used and terminal output

```console
nextflow run nf-core/fastquorum -profile test,docker --outdir profile_test_run

nextflow run nf-core/fastquorum -profile test,docker --outdir profile_test_run --ref_fasta hs37d5.fa -r dev
```

### System information

Ubuntu 20.04.5 LTS

**Comment by nh13** [comment]
@Anushi see https://github.com/nf-core/fastquorum/pull/30 where we've updated the test config
