### ISSUE TITLE
Cannot skip  BWA index generation

### ISSUE THREAD

**Issue by lbeltrame** [nf-core/fastquorum#56]
### Description of the bug

I'm testing fastquorum to as a complement to existing data, therefore I must use the same sequences and index that I used with the previous data.

However as far as I can make out from the code `PREPARE_GENOME` runs unconditionally and generates a BWA index regardless if it's specified or not in the parameters (`bwa`): there are neither conditional checks nor `task.ext.when` definitions to skip this part.

### System information

- Nextflow: 23.04.2
- Hardware: HPC
- Executor: slrum
- Container Engine: apptainer
- OS: Debian
- nf-core/fastquorum version: 1.0.0

**Comment by lbeltrame** [comment]
I had to add `ext.when = { !params.bwa }` to modules.conf to skip this part, however I would like to know first if it's worth sending a PR or not.

**Comment by SPPearce** [comment]
Completed in #58
