### ISSUE TITLE
ZipperBams tags to reverse

### ISSUE THREAD

**Issue by tobyaicher** [nf-core/fastquorum#9]
### Description of the bug

Hi,

I wanted to ask why tags-to-reverse and tag-to-revcomp is set to Consensus in zipperbams after both uncollapsed and collapsed alignment.

In the best practices, this these arguments are only used for the collapsed alignment.

But here both ALIGN_RAW_BAM and ALIGN_CONSENSUS_BAM use tags-to-reverse and tag-to-revcomp set to consensus (as both come from the ALIGN_BAM module). 

Will this impact the pipeline at all if you set tags-to-reverse as consensus when you use zipperbams after the uncollapsed alignment? Do you recommend having this argument for zipperbams after uncollapsed alignment or does it not matter either way?

Thank you!

**Comment by nh13** [comment]
It shouldn't matter for the raw reads as those tags don't exist, but yes, we could optimize it so those options aren't set for the raw reads.

**Comment by nh13** [comment]
It's a no-op for raw reads, so keeping it in for now.
