### ISSUE TITLE
Add support for .fastq file format.

### ISSUE THREAD

**Issue by Pg-Pi3Gey** [nf-core/fastquorum#91]
### Description of feature

The current version 1.0.1 only supports compressed file formats, specifically `.fastq.gz` and `.fq.gz`. If users try to use raw .fastq files, the system will throw an error, indicating that the file names cannot contain spaces and must have the `.fq.gz` or `.fastq.gz` extension.

For example:
```bash
* -- Entry 1 - fastq_2: FastQ file for reads 2 cannot contain spaces and must have extension '.fq.gz' or '.fastq.gz' (s3://samplebucket/SRR22795549_2.fastq)
* -- Entry 1 - fastq_1: FastQ file for reads 1 must be provided, cannot contain spaces and must have extension '.fq.gz' or '.fastq.gz' (s3://samplebucket/SRR22795549_1.fastq)
```

**Comment by SPPearce** [comment]
Completed in [v1.1.0](https://github.com/nf-core/fastquorum/releases/tag/1.1.0)
