### ISSUE TITLE
params.yaml duplex_seq

### ISSUE THREAD

**Issue by lauren-tjoeka** [nf-core/fastquorum#92]
Hi!

In the params.yaml where you can specify if `duplex_seq: true` is this referring to whether the data is paired-end or is it referring to whether the UMI scheme is single-stranded or not? 

For example I have paired-end data from the Agilent SureSelect XT HS library prep kit but the UMI is single-stranded in I2. In the params.yaml would I specify `duplex_seq: false`?

Many thanks!

**Comment by SPPearce** [comment]
Duplex sequencing is where you have a UMI on each original strand of the molecule, and you require to have sequenced reads from both strands of the original DNA and them to have the same UMIs. This decreases the error rate (but also decreases the sequencing depth, as you have to have captured sufficient copies of each strands).
Nothing to do with paired-end sequencing, although paired-end sequencing is required to be able to perform duplex sequencing.
